services:
  - type: web
    name: bronx-ultra-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: API_ID
        value: "31968824"
      - key: API_HASH
        value: "d9847a6694b961248f4052d16b89b912"
      - key: SESSION_STRING
        sync: false
